// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import SupabaseAuthController from "./supabase_auth_controller"
application.register("supabase-auth", SupabaseAuthController)
